files_to_sync:
    - complyctl.spec
    - .packit.yaml

upstream_package_name: complyctl
upstream_tag_template: v{version}
specfile_path: complyctl.spec

downstream_package_name: complyctl

jobs:
- job: copr_build
  trigger: pull_request
  targets:
    - fedora-42-x86_64
    - fedora-rawhide-x86_64
    - centos-stream-9-x86_64
    - centos-stream-10-x86_64
